language: Ruby
rvm:
  - 2.3

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libsqlite3-dev
  - gem update

install:
  - sudo apt-get install ruby-dev
  - gem install bundler
  - bundler install --with=travis

script:
  - rake test


branches:
  only:
  - master
  - batebates

addons:
    code_climate:
        repo_token: 3ad359967ad2924ee23cb4e0f0d10c98d6b9e1f9

after_success:
- bundle exec codeclimate-test-reporter  
